---
  - name: Ensures ~/ dir exists
    file: path=/home/ubuntu/mongodb/backup/calc state=directory
    ignore_errors: yes

  - name: Get mongo pod name
    shell: kubectl get pods --no-headers=true | grep calc-mongodb | cut -c 1-29
    register: mongopod
    ignore_errors: yes

  - name: Collection backup/dump
    shell: kubectl exec -it "{{ mongopod.stdout }}" -- mongodump --collection histories --db calc --out ./mongodb/backup
    ignore_errors: yes

  - name: Copy collection backup from container to container host
    shell: kubectl cp "{{ mongopod.stdout }}":mongodb/backup/calc/histories.bson /home/ubuntu/mongodb/backup/calc/histories.bson
    ignore_errors: yes

  - name: Remove collection from container
    shell: kubectl exec "{{ mongopod.stdout }}" -- sh -c 'rm -rf mongodb/backup/calc/histories.bson'
    ignore_errors: yes
 
  - name: Copy collection from host to local host
    fetch:
      src: /home/ubuntu/mongodb/backup/calc/histories.bson
      dest: ./mongodb/backup/calc/
      flat: yes
    ignore_errors: yes

  # - name: Remove the histories.bson file
  #   shell: rm /home/ubuntu/mongodb/backup/calc/histories.bson

