---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  config: |
    upstream frontend {
        server 10.103.151.221:7080 fail_timeout=0;
    }

    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass http://frontend;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: config-vol
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config-vol
          configMap:
            name: proxy-config
            items:
              - key: config
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 80
